In [7]:
import pandas as pd
from openpyxl import load_workbook

In [10]:
df = pd.read_csv('Walmart_Sales.csv')
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, format='%d-%m-%Y')

In [11]:
month = df["Date"].dt.month
df_pivot = df.copy()
df_pivot['Month'] = month

In [12]:
pivot_table= df_pivot.pivot_table(index='Store', 
                                   columns='Holiday_Flag', 
                                   values='CPI', 
                                   aggfunc='sum').round(1)
pivot_table.sort_values(by=1, ascending=False)

Holiday_Flag        0       1
Store
9             29215.0  2191.6
8             29190.1  2189.7
11            29183.7  2189.3
3             29183.7  2189.3
6             28939.2  2170.9
5             28807.8  2161.1
1             28732.2  2155.4
2             28685.5  2151.9
21            28685.5  2151.9
30            28685.5  2151.9
31            28685.5  2151.9
36            28563.5  2142.8
37            28563.5  2142.8
39            28563.5  2142.8
25            27806.5  2086.0
20            27806.5  2086.0
43            27633.1  2073.0
7             25758.2  1935.8
32            25758.2  1935.8
41            25758.2  1935.8
16            25758.2  1935.8
14            24779.8  1859.0
45            24779.8  1859.0
27            18491.2  1387.4
22            18491.2  1387.4
35            18491.2  1387.4
19            17970.0  1348.3
26            17970.0  1348.3
29            17970.0  1348.3
40            17970.0  1348.3
15            17970.0  1348.3
18            17970.0  1348.3
24            17970.0  1348.3
23            17970.0  1348.3
12            17116.4  1284.8
10            17116.4  1284.8
4             17116.4  1284.8
13            17116.4  1284.8
17            17116.4  1284.8
28            17116.4  1284.8
33            17116.4  1284.8
34            17116.4  1284.8
38            17116.4  1284.8
42            17116.4  1284.8
44            17116.4  1284.8

In [13]:
pivot_table.to_excel('Report.xlsx', sheet_name='WeeklySales')

In [2]:
wb = load_workbook('Report.xlsx')
sheet = wb['WeeklySales']

In [5]:
min_column = wb.active.min_column
max_column = wb.active.max_column
min_row = wb.active.min_row
max_row = wb.active.max_row

In [6]:
min_column, max_column, min_row, max_row

(1, 3, 1, 46)